#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

if ynh_hide_warnings yunohost service status $app-rtorrent >/dev/null; then
	yunohost service remove $app-rtorrent
fi

ynh_config_remove_systemd
ynh_config_remove_systemd "$app-rtorrent"

ynh_config_remove_nginx

# Remove metapackage and its dependencies
dpkg -r flood

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
