#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi
# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app-rtorrent >/dev/null; then
	yunohost service remove $app-rtorrent
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd
ynh_config_remove_systemd "$app-rtorrent"

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove metapackage and its dependencies
dpkg -r flood

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
