#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"
ynh_systemctl --service=$app-rtorrent --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

mkdir -p "$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

tmpdir="$(mktemp -d)"
ynh_setup_source --dest_dir="$tmpdir" --full_replace
dpkg -i $tmpdir/flood-linux.deb
ynh_safe_rm "$tmpdir"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

ynh_config_add_nginx

ynh_config_add_systemd  --template="flood.service"
ynh_config_add_systemd --service=$app-rtorrent --template="rtorrent.service"

yunohost service add $app
yunohost service add $app-rtorrent --needs_exposed_ports $port_rt

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"
ynh_systemctl --service=$app-rtorrent --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
